#!/bin/bash
UPFOLDER=~/Download/.tmp/cridate
CFGFILE=$UPFOLDER/cri.cfg
echo "0"
VERSIONURL="https://raw.githubusercontent.com/Pseudonymous-coders/CRI/master/globs/cri.cfg"
COMURL="https://raw.githubusercontent.com/Pseudonymous-coders/CRI/master/chrootlib"
if [ ! -d "$UPFOLDER" ]; then
	mkdir -p $UPFOLDER > /dev/null 2>&1
	sudo chmod -R 755 $UPFOLDER > /dev/null 2>&1
fi
if [ ! -e "$CFGFILE" ]; then
  sudo touch $CFGFILE > /dev/null 2>&1
  sudo echo "VERSION0.0ENDVERSION...NAMEnoneENDNAME...DATE1/1/16ENDDATE" > $CFGFILE
fi
echo "5"
printf "y\ny\ny\n" | apt-get install git > /dev/null 2>&1
echo "8"
mkdir -p $UPFOLDER/tmpStore > /dev/null 2>&1
cd $UPFOLDER/tmpStore > /dev/null 2>&1
chmod -R 755 ../* > /dev/null 2>&1
chown -R root:root ../* > /dev/null 2>&1
rm -rf .git > /dev/null 2>&1
echo "14"
git config --global user.email "pseudonymous.coders@gmail.com" > /dev/null 2>&1
git config --global user.name "Pseudonymous_Coders" > /dev/null 2>&1
sleep 1 > /dev/null 2>&1
git init > /dev/null 2>&1
sleep 1 > /dev/null 2>&1
git remote add -f origin "https://github.com/Pseudonymous-coders/CRI.git" > /dev/null 2>&1
sleep 0.2 > /dev/null 2>&1
git config core.sparseCheckout true > /dev/null 2>&1
chown -R $USER:$USER ../ > /dev/null 2>&1
chmod -R 755 ../ > /dev/null 2>&1
echo "localSite/" >> .git/info/sparse-checkout
echo "38"
git pull --depth=1 origin master > /dev/null 2>&1
git fetch --all > /dev/null 2>&1
git reset --hard origin/master > /dev/null 2>&1
echo "70"
sudo rm -rf /var/www/* > /dev/null 2>&1
echo "75"
mv localSite/* /var/www/ > /dev/null 2>&1
rm -rf localSite > /dev/null 2>&1
echo "85"
printf 'y\ny\ny\n' | apt-get install -f --fix-missing > /dev/null 2>&1
printf 'y\ny\ny\n' | apt-get install dialog lxappearance thunar numix-gtk-theme numix-icon-theme-circle git > /dev/null 2>&1
printf 'y\ny\ny\n' | apt-get update > /dev/null 2>&1
printf 'y\ny\ny\n' | apt-get upgrade > /dev/null 2>&1
sleep 0.2 > /dev/null 2>&1
echo "90"
wget https://raw.githubusercontent.com/Pseudonymous-coders/CRI/master/chrootlib/cri -O /etc/init.d/cri > /dev/null 2>&1
chmod 755 /etc/init.d/cri > /dev/null 2>&1
sleep 0.1 > /dev/null 2>&1
update-rc.d -f cri remove > /dev/null 2>&1
sleep 0.1 > /dev/null 2>&1
update-rc.d cri defaults > /dev/null 2>&1
echo "93"
wget "$COMURL/updatecri" --no-check-certificate -q -O /usr/bin/updatecri > /dev/null 2>&1
echo "99"
VARR=$(wget "$VERSIONURL" --no-check-certificate -q -O -)
echo $VARR > $CFGFILE
chmod 755 $CFGFILE > /dev/null 2>&1
chown root:root $CFGFILE > /dev/null 2>&1
echo "100"
sleep 5 > /dev/null 2>&1
service cri stop > /dev/null 2>&1
service cri start > /dev/null 2>&1
