#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing autoconf..."
cd $CPKG
installer "ftp://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz" $CPKG/autoconf.tar.xz
sudo tar -xf autoconf.tar.xz
sudo chown $USER:$USER "autoconf-2.69"
cd "autoconf-2.69"
sudo chmod 755 *
sudo chown $USER:$USER *
./configure
make
make install
cd ..
sudo rm -rf "autoconf-2.69" 2&>/dev/null
cleaner $CBUILD # Clean up files
echo "Done"
