#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing bz2..."
cd $CPKG
echo "$CPKG"
installer "http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz" $CPKG/bz2.tar.gz
unpacker "bz2.tar.gz" $CBUILD
cd "$CBUILD/bzip2-1.0.6"
make -f Makefile-libbz2_so
make install
#cleaner $CBUILD # Clean up files
echo "Done"
