#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing cmake..."
cd $CPKG
echo "$CPKG"
installer "http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz" $CPKG/cmake.tar.gz
unpacker "cmake.tar.gz" $CBUILD
cd $CBUILD
#sudo cp -r usr/local/ /usr/  # Move all of the files
sudo ./configure --prefix=/usr/local
sudo make
sudo make install
cleaner $CBUILD # Clean up files
