#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing cmake..."
cd $CPKG
echo "$CPKG"
installer "http://www.cmake.org/files/v3.0/cmake-3.0.2.tar.gz" $CPKG/cmake.tar.gz
unpacker "cmake.tar.gz" $CBUILD
cd "$CBUILD/cmake-3.0.2"
#sudo cp -r usr/local/ /usr/  # Move all of the files
sudo su -c './configure --prefix=/usr/local; make; make install'
cleaner $CBUILD # Clean up files
echo "Done"
