#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing fixcri..."
cd $CPKG
installer "https://raw.githubusercontent.com/Pseudonymous-coders/CRI/master/com/fixcri" $CPKG/fixcri
sudo chown $USER:$USER fixcri
sudo chmod 755 *
sudo cp -r fixcri /usr/local/bin/
sudo chown $USER:$USER /usr/local/bin/fixcri
sudo chmod 755 /usr/local/bin/fixcri
cleaner $CBUILD # Clean up files
echo "Done"
