#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing chroot..."
cd $CTEMP
installer "$URLCROUTON" $CTEMP/crouton
echo "Downloading...."
if [ ! -d "$CROUTON" ]; then #Installs crouton
	sudo su -c "sudo echo "chrooter\nbinner\n" | sh crouton -r trusty -t xiwi,extension,e17"
else
	sudo su -c "sudo echo "chrooter\nbinner\n" | sh crouton -r trusty -t xiwi,extension,e17 -u"
fi

echo "user\n"
echo "password\n"

cleaner $CBUILD # Clean up files
echo "Done"
