#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing chroot..."
cd $CTEMP
installer "$URLCROUTON" $CTEMP/crouton
echo "Downloading...."
if [ ! -d "$CROUTON" ]; then #Installs crouton
	sudo su -c "sudo echo 'chrooter binner' | sh crouton -r trusty -t xiwi,extension,e17"
else
	sudo su -c "sudo echo 'chrooter binner' | sh crouton -r trusty -t xiwi,extension,e17 -u"
fi

echo "user\n"
echo "password\n"

wait

sudo su -c "sudo echo 'y chrooter binner' | sudo enter-chroot -u root"
sudo su -c "sudo echo 'y chrooter binner' | sudo enter-chroot -u root" # Make sure everythin is installed and setup script is broken

sleep 5

cleaner $CBUILD # Clean up files
echo "Done"
