#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing gawk (May take a while)..."
cd $CPKG
installer "http://ftp.gnu.org/gnu/gawk/gawk-4.1.1.tar.gz" $CPKG/gawk.tar.gz
unpacker "gawk.tar.gz" $CPKG
sudo chown $USER:$USER "gawk-4.1.1"
cd "gawk-4.1.1"
./configure --prefix=/usr/local
make
sudo cp -r gawk /usr/local/bin
cd ..
sudo rm -rf "gawk-4.1.1" 2&>/dev/null
cleaner $CBUILD # Clean up files
echo "Done"
