#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing glibc..."
cd $CPKG
echo "$CPKG"
if [[ "$ARCH" == "i686" ]];then
    installer "https://dl.dropboxusercontent.com/s/dic47f8eqxhpf89/glibc-2.17.90-baseline-chromeos-i686.tar.gz?token_hash=AAHx_77YtWLLnkjCJRaCJt7RsdKrfkT6lgKS9BZc4O-0Pg&dl=1" $CPKG/glibc.tar.gz
elif [[ "$ARCH" == "x86_64" ]];then 
    installer "https://dl.dropboxusercontent.com/s/x3tu160i7pmn6tp/glibc-2.17-baseline-chromeos-x86_64.tar.gz?token_hash=AAG794JG65HjzHMcAyAysQUbEPMUci1bZJPREj3ztCtnBg&dl=1" $CPKG/glibc.tar.gz
fi

unpacker "glibc.tar.gz" $CBUILD

cd $CBUILD
sudo cp -r usr/local/ /usr/  # Move all of the files
cleaner $CBUILD
echo "Done"
