#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing help2man (May take a while)..."
cd $CPKG
installer "http://reflection.oss.ou.edu/gnu/gnu/help2man/help2man-1.43.3.tar.gz" $CPKG/helpman.tar.gz
unpacker "helpman.tar.gz" $CPKG
sudo chown $USER:$USER "help2man-1.43.3"
cd "help2man-1.43.3"
./configure --prefix=/usr/local --host=$ARCH
make
make install
cd ..
sudo rm -rf "help2man-1.43.3" 2&>/dev/null
cleaner $CBUILD # Clean up files
echo "Done"
