#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing libsigsegv (May take a while)..."
cd $CPKG
installer "ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz" $CPKG/libsigsegv.tar.gz
unpacker "libsigsegv.tar.gz" $CPKG
sudo chown $USER:$USER "libsigsegv-2.10"
cd "libsigsegv-2.10"
sudo chown $USER:$USER *
sudo chmod 755 *
if [[ "$ARCH" == "i686" ]];then
 ./configure --libdir=/usr/local/lib32/ CC="gcc -m32" CFLAGS=" -fPIC"
elif [[ "$ARCH" == "x86_64" ]];then 
 ./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"
fi
make
make check
sudo cp -r libtool /usr/local/bin
#cleaner $CBUILD # Clean up files
echo "Done"
