#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing libtoolize (May take a while)..."
cd $CPKG
sudo git clone git://git.savannah.gnu.org/libtool.git
sudo chown $USER:$USER "libtool"
cd "libtool"
sudo chown $USER:$USER *
sudo chmod 755 *
./bootstrap
sleep 0.5
sudo chown $USER:$USER *
sudo chmod 755 *
./configure --prefix=/usr/local --host=$ARCH
sleep 1
make
sleep 0.1
make install
cd ..
sudo rm -rf "libtool" 2&>/dev/null
cleaner $CBUILD # Clean up files
echo "Done"
