#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing ncurses..."
cd $CPKG
installer "ftp://ftp.gnu.org/pub/gnu/ncurses/ncurses-5.9.tar.gz" $CPKG/ncurses.tar.gz
unpacker "ncurses.tar.gz" $CBUILD
cd "$CBUILD/ncurses-5.9"
./configure CFLAGS=\" -fPIC\" --without-debug --prefix=/usr/local
make
make install
cleaner $CBUILD # Clean up files
echo "Done"
