#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing perl..."
cd $CPKG
if [[ "$ARCH" == "i686" ]];then
    installer "https://dl.dropboxusercontent.com/s/qwbwhvqed0yyv3l/perl-5.16.3-chromeos-i686.tar.gz?token_hash=AAHjq1OrZ3iNYerA9y6QIPtsn3fOnW5QeIFbYlBbBN-OkA&dl=1" $CPKG/perl.tar.gz
elif [[ "$ARCH" == "x86_64" ]];then 
    installer "https://dl.dropboxusercontent.com/s/gg2q9tsvy2ybf80/perl-5.18.1-chromeos-x86_64.tar.gz?token_hash=AAFbAeYB604esg7FRBM_TeBh2hiDg2Bw8eZfPHFH8zCdHw&dl=1" $CPKG/perl.tar.gz
fi

unpacker "perl.tar.gz" $CBUILD

cd $CBUILD
sudo cp -r usr/local/ /usr/  # Move all of the files
cleaner $CBUILD # Clean up files
echo "Done"
