#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing python 2.7..."
cd $CPKG
installer "https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz" $CPKG/python27.tar.gz
unpacker "python27.tar.gz" $CPKG
sudo chown $USER:$USER "Python-2.7.10"
cd "Python-2.7.10"
sudo chown $USER:$USER *
sudo chmod 755 *
fixowner
./configure --prefix=/usr/local CPPFLAGS="-I/usr/local/include -I/usr/local/include/ncurses" LDFLAGS="-L/usr/local/lib" CFLAGS=" -fPIC" $1
make $2
make check
make install $2
#sudo mv python python27
#sudo cp -r python27 /usr/local/bin
#sudo mv "Python-2.7.10/" "python2.7"
cleaner $CBUILD # Clean up files
echo "Done"
