#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing python..."
cd $CPKG
if [[ "$ARCH" == "i686" ]];then
    installer "https://dl.dropboxusercontent.com/s/mxgfmq992hhiawk/python-3.3.2-chromeos-i686.tar.gz?token_hash=AAFA2YzFp293uyV3zYfP70iwCk8oH9HCLKMTrK0dtMU8GQ&dl=1" $CPKG/python.tar.gz
elif [[ "$ARCH" == "x86_64" ]];then 
    installer "https://dl.dropboxusercontent.com/s/r1zvmza51hrr87q/python-3.3.2-chromeos-x86_64.tar.gz?token_hash=AAHIdz6pWcOrfty7C8ACuRcLDq0d0ERYs0jCgOPLn5USUQ&dl=1" $CPKG/python.tar.gz
fi

unpacker "python.tar.gz" $CBUILD

cd $CBUILD
sudo cp -r usr/local/ /usr/  # Move all of the files
cleaner $CBUILD # Clean up files
