#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing rootmount..."
cd $CPKG
installer "https://raw.githubusercontent.com/Pseudonymous-coders/CRI/master/com/rootmount" $CPKG/rootmount
sudo cp -r rootmount /usr/local/bin/
cleaner $CBUILD # Clean up files
echo "Done"
