#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing texinfo (May take a while)..."
cd $CPKG
installer "http://ftp.gnu.org/gnu/texinfo/texinfo-4.5.tar.gz" $CPKG/texinfo.tar.gz
unpacker "texinfo.tar.gz" $CPKG
sudo chown $USER:$USER "texinfo-4.5"
cd "texinfo-4.5"
./configure --prefix=/usr/local --host=$ARCH
make
make install
cd ..
sudo rm -rf "texinfo-4.5" 2&>/dev/null
cleaner $CBUILD # Clean up files
echo "Done"
