#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing commandWriter..."
cd $CPKG
installer "https://raw.githubusercontent.com/Pseudonymous-coders/CRI/master/com/writer" $CPKG/writer
sudo chown $USER:$USER writer
sudo chmod 755 *
sudo cp -r writer /usr/local/bin/
sudo chown $USER:$USER /usr/local/bin/writer
sudo chmod 755 /usr/local/bin/writer
cleaner $CBUILD # Clean up files
echo "Done"
