#!/bin/bash
CGLOBS=~/Downloads/.tmp/globs
source $CGLOBS/globvar
source $CGLOBS/globfun
echo "
Installing zlibpkg..."
cd $CPKG
if [[ "$ARCH" == "i686" ]];then
    installer "https://dl.dropboxusercontent.com/s/ljhhvr12u1izayj/zlib-1.2.8-chromeos-i686.tar.gz?token_hash=AAEABTatYkxOOybZGoCj3Kg_DKEbFbSfolzZklfHwCsP_A&dl=1" $CPKG/zlibpkg.tar.gz
elif [[ "$ARCH" == "x86_64" ]];then 
    installer "https://dl.dropboxusercontent.com/s/h4lqj0rnand0jqu/zlib-1.2.8-chromeos-x86_64.tar.gz?token_hash=AAGabAMhX4CGpzhpkcuKMmmWPxFZDiNOC-r9B0o7x4D7eQ&dl=1" $CPKG/zlibpkg.tar.gz
fi

unpacker "zlibpkg.tar.gz" $CBUILD

cd $CBUILD
sudo cp -r usr/local/ /usr/  # Move all of the files
cleaner $CBUILD # Clean up files
echo "Done"
