#!/bin/bash

ask() { # We don't want to import GLOBS for coms
    while true; do
        read -p "$1?[y/n] " REPLY </dev/tty
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

part ()
{
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification 2>/dev/null | sed -n '9p' 2>/dev/null | sed -n -e 's/^.*titions //p' 2>/dev/null
}
  sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions $(part)
  sudo su -c "crossystem dev_boot_signed_only=0;mount -o remount,rw /"
  echo "If this was a succesful time running rootmount, you're done!
  If you haven't please run the second part of the install script located in your downloads folder like so >
  
  sudo ~/Downloads/install2.sh
  "
 if ask "We need to reboot is that okay"; then
    sudo reboot
 fi
