#!/bin/bash

# This file is to delete all DPKG cache and is made to make sure you have
# A fresh start and redo it dude

CACHE_FOLDER=/var/lib/dpkg
EDITORS="David Smerkous and Eli Smith"
LASTMODIFIED="4/14/2016"

echo "
Starting DPKG cleaner and CACHE wiper
Created by: $EDITORS
Last Modified: $LASTMODIFIED
Cache folder: $CACHE_FOLDER
"
echo "crontab fix"
sudo sed -i '/crontab/d' $CACHE_FOLDER/statoverride & # If the user has multiple files, lets not ruin them and remove
echo "done..."
# The crontab, which screws it all up

if [ $(grep -i "crontab" $CACHE_FOLDER/statoverride) ]; then
  echo "'crontab' not moving, deleting file!"
  sudo rm -rf $CACHE_FOLDER/statoverride
  sudo touch $CACHE_FOLDER/statoverride
  echo "Recreated empty crontab user"
fi

echo "override file fixed
Trying to fix cache files (Refresh)
"
cd $CACHE_FOLDER

sudo rm -rf available
sudo rm -rf status
sudo rm -rf diversions
sudo rm -rf info
sudo rm -rf *-old

sudo mkdir info
sudo touch available
sudo touch status
sudo touch diversions
echo "Refreshed, updating diversions"
sleep 0.1
sudo su -c 'printf "dash\n/bin/sh\n/bin/sh/distrib\n/dash\n" > diversions'
# EOF